[book]
authors = ["Rob Moss"]
language = "en"
multilingual = false
src = "src"
title = "Git is my lab book"

[preprocessor.admonish]
command = "mdbook-admonish"

[output.html]
additional-css = ["mdbook-admonish.css"]
git-repository-url = "https://github.com/robmoss/git-is-my-lab-book"
edit-url-template = "https://github.com/robmoss/git-is-my-lab-book/edit/master/{path}"
