[book]
authors = ["Rob Moss"]
language = "en"
multilingual = false
src = "src"
title = "Git is my lab book"

[preprocessor.admonish]
command = "mdbook-admonish"

[output.html]
additional-css = ["mdbook-admonish.css"]
